import Head from "next/head";
import { Button } from "primereact/button";
import { Card } from "primereact/card";
import { Divider } from "primereact/divider";
import { InputText } from "primereact/inputtext";
import { OrderList } from "primereact/orderlist";
import { useEffect, useState } from "react";

export default function Home() {
  const [todos, addTodo] = useState([]);

  useEffect(() => {
    console.log(todos);
  }, [todos]);

  const itemTemplate = (item, i) => {
    return (
      <div className="flex  justify-content-between p-1 align-items-center gap-8">
        <span className="font-bold text-900">{item}</span>
        <Button
          style={{ background: "#212121" }}
          size="small"
          icon={<i className="pi pi-trash"></i>}
          onClick={() => {
            let i = todos.findIndex((x) => x === item);
            todos.splice(i, 1);

            addTodo([...todos]);
          }}
        />
      </div>
    );
  };

  return (
    <>
      <Head>
        <title>toDoListApp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex justify-content-center align-items-center h-screen w-full">
          <Card
            style={{
              background: "#f0fdfa",
              color: "#212121", height:"80vh",
            }}
            className="w-12 text-center md:w-6"
            title="toDoListApp"
          >
            <InputText
              style={{ background: "#616161", color: "#FFFFFF" }}
              className="w-full"
              onKeyDown={(e) => {
                if (e.key === "Enter") {
                  addTodo([...todos, e.target.value]);
                  e.target.value = "";
                }
              }}
            />
            <Divider />

            <div className="card flex justify-content-center">
              {todos.length > 0 ? (
                <OrderList
                  value={todos}
                  onChange={(e) => addTodo(e.value)}
                  itemTemplate={itemTemplate}
                  dragdrop
                  style={{width:"80vw"}}
                />
              ) : (
                <div>It seems like a bit quiet here 🥱</div>
              )}
            </div>
          </Card>
        </div>
      </main>
    </>
  );
}
